---

# FILE:            {{ role_path }}/tasks/hosts/main.yml
# LICENSE:         Public Domain
# SEE:             https://serverfault.com/questions/832799/ansible-add-ip-of-all-hosts-to-etc-hosts-of-all-other-hosts

- name: "[system] hostname | require minimum length and enforce a valid RFC822 value"
  set_fact:
    a2s_hostname_rfc822: "{{ a2s_hostname | replace('_', '-') }}"
  when:
    - "(a2s_hostname is defined) and (a2s_hostname | length > 2)"
  tags:
    - a2s-hostname

# TODO: fix 'ignore_errors: yes' (fititnt, 2020-01-06 21:02)
- name: "[system] hostname | set hostname"
  hostname:
    name: "{{ a2s_hostname_rfc822 }}"
    use: "{{ a2s_internal_hostname_use | default(omit) }}"
  # ignore_errors: yes
  ignore_errors: "{{ a2s_isconteiner | default(false) }}"
  become: yes
  when:
    - "(a2s_hostname_rfc822 is defined)"
  notify:
    - "a2s-hostname changed"
  tags:
    - a2s-hostname-hostname