---

# FILE:            {{ role_path }}/tasks/sample-content-php/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/file_module.html
# SEE:             https://docs.ansible.com/ansible/latest/modules/copy_module.html

- name: "sample-content-php | directory: create/modify base path"
  file:
    state: directory
    recurse: "{{ item.recurse | default('yes') }}"
    path: "{{ item.dest }}"
    owner: "{{ item.owner | default(a2s_default_user) }}"
    group: "{{ item.owner | default(a2s_default_group) }}"
    mode: "{{ item.mode | default(a2s_default_directory_mode) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(omit) }}"
  with_items: "{{ a2s_sample_content_phps }}"

- name: "sample-content-php | copy contents"
  copy:
    src: "{{ role_path }}/files/php/"
    dest: "{{ item.dest }}"
    attributes: "{{ item.attributes | default(omit) }}"
    backup: "{{ item.backup | default(omit) }}"
    checksum: "{{ item.checksum | default(omit) }}"
    content: "{{ item.content | default(omit) }}"
    decrypt: "{{ item.decrypt | default(omit) }}"
    directory_mode: "{{ item.directory_mode | default(omit) }}"
    follow: "{{ item.follow | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    group: "{{ item.owner | default(a2s_default_group) }}"
    local_follow: "{{ item.local_follow | default(omit) }}"
    mode: "{{ item.mode | default(a2s_default_directory_mode) }}"
    owner: "{{ item.owner | default(a2s_default_user) }}"
    remote_src: "{{ item.remote_src | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(omit) }}"
    validate: "{{ item.validate | default(omit) }}"
  with_items: "{{ a2s_sample_content_phps }}"
