---

# FILE:            {{ role_path }}/tasks/file/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/file_module.html
# SEE:             https://docs.ansible.com/ansible/latest/modules/win_file_module.html

- name: "[files] a2s_files | Via: debug | a2s_files_default"
  debug:
    msg: "{{ a2s_files_default }}"

- name: "[files] a2s_files | Via: file | (*nix only) Manage files and file properties"
  file:
    path: "{{ item.path | default(a2s_files_default.path | default(omit)) }}"
    dest: "{{ item.dest | default(a2s_files_default.dest | default(omit)) }}" # alias for path
    name: "{{ item.name | default(a2s_files_default.name | default(omit)) }}" # alias for path
    src: "{{ item.src | default(a2s_files_default.src | default(omit)) }}"
    state: "{{ item.src | default(a2s_files_default.src | default(omit)) }}" # We omit state

    # Other parameters, by alphabetical order
    access_time: "{{ item.access_time | default(a2s_files_default.access_time | default(omit)) }}"
    access_time_format: "{{ item.access_time_format | default(a2s_files_default.access_time_format | default(omit)) }}"
    attributes: "{{ item.attributes | default(a2s_files_default.attributes | default(omit)) }}"
    attr: "{{ item.attr | default(a2s_files_default.attr | default(omit)) }}" # alias for attributes
    follow: "{{ item.follow | default(a2s_files_default.follow | default(omit)) }}"
    force: "{{ item.force | default(a2s_files_default.force | default(omit)) }}"
    group: "{{ item.group | default(a2s_files_default.group | default(omit)) }}"
    mode: "{{ item.mode | default(a2s_files_default.mode | default(omit)) }}"
    modification_time: "{{ item.modification_time | default(a2s_files_default.modification_time | default(omit)) }}"
    modification_time_format: "{{ item.modification_time_format | default(a2s_files_default.modification_time_format | default(omit)) }}"
    owner: "{{ item.owner | default(a2s_files_default.owner | default(omit)) }}"
    recurse: "{{ item.recurse | default(a2s_files_default.recurse | default(omit)) }}"
    selevel: "{{ item.selevel | default(a2s_files_default.selevel | default(omit)) }}"
    serole: "{{ item.serole | default(a2s_files_default.serole | default(omit)) }}"
    setype: "{{ item.setype | default(a2s_files_default.setype | default(omit)) }}"
    seuser: "{{ item.seuser | default(a2s_files_default.seuser | default(omit)) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(a2s_files_default.unsafe_writes | default(omit)) }}"
  with_items: "{{ a2s_files }}"
  when:
    - "(item.content is not defined) or (item.content | length < 1)"
    - "(a2s_internal_iswindows is undefined)
      or (a2s_internal_iswindows|bool is sameas false)"
  notify:
    - "a2s-files changed"
  tags:
    - a2s-files

- name: "[files] a2s_files | Via: win_file | (Windows only): Manage files and file properties"
  win_file:
    path: "{{ item.path | default(a2s_files_default.path | default(omit)) }}"
    state: "{{ item.state | default(a2s_files_default.state | default(omit)) }}"
  with_items: "{{ a2s_files }}"
  when:
    - "(item.content is not defined) or (item.content | length < 1)"
    - "(a2s_internal_iswindows is defined)
      and (a2s_internal_iswindows|bool is sameas true)"
  notify:
    - "a2s-files changed"
  tags:
    - a2s-files

- name: "[files] a2s_files | Via: copy | (*nix only) (a2s_files[n]content defined EXPLICITLY) create/delete file with content"
  copy:
    dest: "{{ item.dest | default(a2s_copies_default.dest | default(omit)) }}"
    src: "{{ item.src | default(a2s_copies_default.src | default(omit)) }}"

    # Other parameters, by alphabetical order
    attributes: "{{ item.dest | default(a2s_copies_default.attributes | default(omit)) }}"
    attr: "{{ item.dest | default(a2s_copies_default.attr | default(omit)) }}" # alias for attributes
    backup: "{{ item.dest | default(a2s_copies_default.backup | default(omit)) }}"
    checksum: "{{ item.dest | default(a2s_copies_default.checksum | default(omit)) }}"
    content: "{{ item.dest | default(a2s_copies_default.content | default(omit)) }}"
    decrypt: "{{ item.dest | default(a2s_copies_default.decrypt | default(omit)) }}"
    directory_mode: "{{ item.dest | default(a2s_copies_default.directory_mode | default(omit)) }}"
    follow: "{{ item.dest | default(a2s_copies_default.follow | default(omit)) }}"
    force: "{{ item.dest | default(a2s_copies_default.force | default(omit)) }}"
    group: "{{ item.dest | default(a2s_copies_default.group | default(omit)) }}"
    local_follow: "{{ item.dest | default(a2s_copies_default.local_follow | default(omit)) }}"
    mode: "{{ item.dest | default(a2s_copies_default.mode | default(omit)) }}"
    owner: "{{ item.dest | default(a2s_copies_default.owner | default(omit)) }}"
    remote_src: "{{ item.dest | default(a2s_copies_default.remote_src | default(omit)) }}"
    selevel: "{{ item.dest | default(a2s_copies_default.selevel | default(omit)) }}"
    serole: "{{ item.dest | default(a2s_copies_default.serole | default(omit)) }}"
    setype: "{{ item.dest | default(a2s_copies_default.setype | default(omit)) }}"
    seuser: "{{ item.dest | default(a2s_copies_default.seuser | default(omit)) }}"
    unsafe_writes: "{{ item.dest | default(a2s_copies_default.unsafe_writes | default(omit)) }}"
    validate: "{{ item.dest | default(a2s_copies_default.validate | default(omit)) }}"
  with_items: "{{ a2s_copies }}"
  when:
    - "(item.content is defined) and (item.content | length > 0)"
    - "(a2s_internal_iswindows is undefined)
      or (a2s_internal_iswindows|bool is sameas false)"
  notify:
    - "a2s-copy-copies changed"
  tags:
    - a2s-copy-copies

- name: "[files] a2s_files | Via: win_copy | (Windows only) (a2s_files[n]content defined EXPLICITLY) create/delete file with content"
  win_copy:
    dest: "{{ item.dest | default(a2s_copies_default.dest | default(omit)) }}"
    src: "{{ item.src | default(a2s_copies_default.src | default(omit)) }}"

    # Other parameters, by alphabetical order
    backup: "{{ item.backup | default(a2s_copies_default.backup | default(omit)) }}"
    content: "{{ item.content | default(a2s_copies_default.content | default(omit)) }}"
    decrypt: "{{ item.decrypt | default(a2s_copies_default.decrypt | default(omit)) }}"
    force: "{{ item.force | default(a2s_copies_default.force | default(omit)) }}"
    local_follow: "{{ item.local_follow | default(a2s_copies_default.local_follow | default(omit)) }}"
    remote_src: "{{ item.remote_src | default(a2s_copies_default.remote_src | default(omit)) }}"
  with_items: "{{ a2s_copies }}"
  when:
    - "(item.content is defined) and (item.content | length > 0)"
    - "(a2s_internal_iswindows is defined)
      and (a2s_internal_iswindows|bool is sameas true)"
  notify:
    - "a2s-copy-copies changed"
  tags:
    - a2s-copy-copies
