---

# FILE:            {{ role_path }}/tasks/mysql/mysql_db/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/mysql_db_module.html

- name: "mysql | mysql_db.yml: Add or remove MariaDB/MySQL databases from a remote host"
  mysql_db:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    client_cert: "{{ item.client_cert | default(omit) }}"
    client_key: "{{ item.client_key | default(omit) }}"
    collation: "{{ item.collation | default(omit) }}"
    config_file: "{{ item.config_file | default(omit) }}"
    connect_timeout: "{{ item.connect_timeout | default(omit) }}"
    encoding: "{{ item.encoding | default(omit) }}"
    ignore_tables: "{{ item.ignore_tables | default(omit) }}"
    login_host: "{{ item.login_host | default(omit) }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_port: "{{ item.login_port | default(omit) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(omit) }}"
    login_user: "{{ item.login_user | default(omit) }}"
    quick: "{{ item.quick | default(omit) }}"
    single_transaction: "{{ item.single_transaction | default(omit) }}"
    target: "{{ item.target | default(omit) }}"
  with_items: "{{ a2s_mysql_dbs }}"
  notify:
    - "a2s-mysql-dbs changed"
  tags:
    - a2s-mysql-dbs