---

# FILE:            {{ role_path }}/tasks/mysql/mysql_user/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/mysql_user_module.html

- name: "[database] mysql | mysql_user.yml: Adds or removes a user from a MariaDB/MySQL database [a2s_mysql_users_defaults: {{ a2s_mysql_users_defaults }}]"
  mysql_user:
    name: "{{ item.name }}"
    state: "{{ item.state | default(a2s_mysql_users_defaults.state | default(omit)) }}"
    append_privs: "{{ item.append_privs | default(a2s_mysql_users_defaults.append_privs | default(omit)) }}"
    ca_cert: "{{ item.ca_cert | default(a2s_mysql_users_defaults.ca_cert | default(omit)) }}"
    check_implicit_admin: "{{ item.check_implicit_admin | default(a2s_mysql_users_defaults.check_implicit_admin | default(omit)) }}"
    client_cert: "{{ item.client_cert | default(a2s_mysql_users_defaults.client_cert | default(omit)) }}"
    client_key: "{{ item.client_key | default(a2s_mysql_users_defaults.client_key | default(omit)) }}"
    config_file: "{{ item.config_file | default(a2s_mysql_users_defaults.config_file | default(omit)) }}"
    connect_timeout: "{{ item.connect_timeout | default(a2s_mysql_users_defaults.connect_timeout | default(omit)) }}"
    encrypted: "{{ item.encrypted | default(a2s_mysql_users_defaults.encrypted | default(omit)) }}"
    host: "{{ item.host | default(a2s_mysql_users_defaults.host | default(omit)) }}"
    host_all: "{{ item.host_all | default(a2s_mysql_users_defaults.host_all | default(omit)) }}"
    login_host: "{{ item.login_host | default(a2s_mysql_users_defaults.login_host | default(omit)) }}"
    login_password: "{{ item.login_password | default(a2s_mysql_users_defaults.login_password | default(omit)) }}"
    login_port: "{{ item.login_port | default(a2s_mysql_users_defaults.login_port | default(omit)) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(a2s_mysql_users_defaults.login_unix_socket | default(omit)) }}"
    login_user: "{{ item.login_user | default(a2s_mysql_users_defaults.login_user | default(omit)) }}"
    password: "{{ item.password | default(a2s_mysql_users_defaults.password | default(omit)) }}"
    priv: "{{ item.priv | default(a2s_mysql_users_defaults.priv | default(omit)) }}"
    sql_log_bin: "{{ item.sql_log_bin | default(a2s_mysql_users_defaults.sql_log_bin | default(omit)) }}"
  with_items: "{{ a2s_mysql_users }}"
  no_log: "{{ a2s_mysql_users_no_log | default(a2s_default_no_log) }}"
  notify:
    - "a2s-mysql-users changed"
  tags:
    - a2s-mysql-users