---

# FILE:            {{ role_path }}/tasks/directory/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/file_module.html
# SEE:             https://docs.ansible.com/ansible/latest/modules/win_file_module.html
# SEE:             https://docs.ansible.com/ansible/latest/modules/win_owner_module.html

- name: "directory | (*nix): add/remove directories"
  file:
    path: "{{ item.path }}"
    state: "{{ item.state | default('directory') }}"
    access_time: "{{ item.access_time | default(omit) }}"
    access_time_format: "{{ item.access_time_format | default(omit) }}"
    attributes: "{{ item.attributes | default(omit) }}"
    follow: "{{ item.follow | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    group: "{{ item.group | default(a2s_default_group) }}"
    mode: "{{ item.mode | default(a2s_default_directory_mode) }}"
    modification_time: "{{ item.modification_time | default(omit) }}"
    modification_time_format: "{{ item.modification_time_format | default(omit) }}"
    owner: "{{ item.owner | default(a2s_default_user) }}"
    recurse: "{{ item.recurse | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(omit) }}"
  with_items: "{{ a2s_directories }}"
  when:
    - "(a2s_internal_iswindows is undefined)
      or (a2s_internal_iswindows|bool is sameas false)"

- name: "directory | (Windows): add/remove directories"
  win_file:
    path: "{{ item.path }}"
    state: "{{ item.state | default('directory') }}"
  with_items: "{{ a2s_directories }}"
  when:
    - "(a2s_internal_iswindows is defined)
      and (a2s_internal_iswindows|bool is sameas true)"
