---

# FILE:            {{ role_path }}/tasks/directory/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/file_module.html
# SEE:             https://docs.ansible.com/ansible/latest/modules/win_file_module.html

- name: "[files] a2s_directories | Via: debug | a2s_directories_default"
  debug:
    msg:
      a2s_directories_default: "{{ a2s_directories_default | to_json }}"
      a2s_directories: "{{ a2s_directories | default('undefined') }}"
  vars:
    # Did Ansible allow NOT evaluate a variable, so this part would not be
    # necessary? (fititnt, 2020-01-20 02:29 BRT)
    item:
      path: '[[ item.path ]]'
      src: '[[ item.src ]]'
      access_time: "[[ item.access_time ]]"
      access_time_format: "[[ item.access_time_format ]]"
      attributes: "[[ item.attributes ]]"
      attr: "[[ item.attr ]]"
      follow: "[[ item.follow ]]"
      force: "[[ item.force ]]"
      mode: "[[ item.mode ]]"
      modification_time: "[[ item.modification_time ]]"
      modification_time_format: "[[ item.modification_time_format ]]"
      owner: "[[ item.owner ]]"
      recurse: "[[ item.recurse ]]"
      selevel: "[[ item.selevel ]]"
      serole: "[[ item.serole ]]"
      setype: "[[ item.setype ]]"
      seuser: "[[ item.seuser ]]"
      unsafe_writes: "[[ item.unsafe_writes ]]"
      var: "[[ item.var ]]"
      var1: "[[ item.var1 ]]"
      var2: "[[ item.var2 ]]"
      var3: "[[ item.var3 ]]"
      a: "[[ item.a ]]"
      b: "[[ item.b ]]"
      c: "[[ item.c ]]"
      x: "[[ item.x ]]"
      y: "[[ item.y ]]"
      z: "[[ item.z ]]"
  # We allow this fail because the user may be using and variable that only
  # exist when evaluating the loop and this variable was not expected.
  ignore_errors: yes

- name: "[files] a2s_directories | Via: file | (*nix only): add/remove directories"
  file:
    path: "{{ item.path | default(a2s_directories_default.path | default(omit)) }}"
    # dest: "{{ item.dest | default(a2s_directories_default.dest | default(omit)) }}" # alias for path
    # name: "{{ item.name | default(a2s_directories_default.name | default(omit)) }}" # alias for path
    src: "{{ item.src | default(a2s_directories_default.src | default(omit)) }}"
    # We set by (last) default 'directory'. Yes, actually users
    # can create/delete non-directories
    state: "{{ item.state | default(a2s_directories_default.state | default('directory')) }}"

    # Other parameters, by alphabetical order
    access_time: "{{ item.access_time | default(a2s_directories_default.access_time | default(omit)) }}"
    access_time_format: "{{ item.access_time_format | default(a2s_directories_default.access_time_format | default(omit)) }}"
    attributes: "{{ item.attributes | default(a2s_directories_default.attributes | default(omit)) }}"
    attr: "{{ item.attr | default(a2s_directories_default.attr | default(omit)) }}" # alias for attributes
    follow: "{{ item.follow | default(a2s_directories_default.follow | default(omit)) }}"
    force: "{{ item.force | default(a2s_directories_default.force | default(omit)) }}"
    group: "{{ item.group | default(a2s_directories_default.group | default(omit)) }}"
    mode: "{{ item.mode | default(a2s_directories_default.mode | default(omit)) }}"
    modification_time: "{{ item.modification_time | default(a2s_directories_default.modification_time | default(omit)) }}"
    modification_time_format: "{{ item.modification_time_format | default(a2s_directories_default.modification_time_format | default(omit)) }}"
    owner: "{{ item.owner | default(a2s_directories_default.owner | default(omit)) }}"
    recurse: "{{ item.recurse | default(a2s_directories_default.recurse | default(omit)) }}"
    selevel: "{{ item.selevel | default(a2s_directories_default.selevel | default(omit)) }}"
    serole: "{{ item.serole | default(a2s_directories_default.serole | default(omit)) }}"
    setype: "{{ item.setype | default(a2s_directories_default.setype | default(omit)) }}"
    seuser: "{{ item.seuser | default(a2s_directories_default.seuser | default(omit)) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(a2s_directories_default.unsafe_writes | default(omit)) }}"
  with_items: "{{ a2s_directories }}"
  when:
    - "(a2s_internal_iswindows is undefined)
      or (a2s_internal_iswindows|bool is sameas false)"
  notify:
    - "a2s-directory-directories changed"
  tags:
    - a2s-directory-directories

- name: "[files] directory | Via: win_file | (Windows): add/remove directories"
  win_file:
    path: "{{ item.path | default(a2s_directories_default.path | default(omit)) }}"

    # We set by (last) default 'directory'. Yes, actually users
    # can create/delete non-directories
    state: "{{ item.src | default(a2s_directories_default.src | default(omit)) }}"
  with_items: "{{ a2s_directories }}"
  when:
    - "(a2s_internal_iswindows is defined)
      and (a2s_internal_iswindows|bool is sameas true)"
  notify:
    - "a2s-directory-directories changed"
  tags:
    - a2s-directory-directories
