---

# FILE:            {{ role_path }}/tasks/etc-hosts/main.yml
# LICENSE:         Public Domain

- name: "etchosts | Append values to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
    state: present
    unsafe_writes: "{{ a2s_internal_isconteiner }}" # If is container, we allow unsafe_writes
  with_items: "{{ a2s_etchosts }}"
  # when:
  #   - "(a2s_etchosts is defined) and (a2s_etchosts[0] is defined)"