---

# FILE:            {{ role_path }}/tasks/etc-hosts/main.yml
# LICENSE:         Public Domain

- name: "[system] etchosts | Append values to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
    state: present
    unsafe_writes: "{{ a2s_internal_isconteiner }}" # If is container, we allow unsafe_writes
  with_items: "{{ a2s_etchosts }}"
  notify:
    - "a2s-etchosts changed"
  tags:
    - a2s-etchosts
