---
# This is a draft. Can be ignored at this moment

# NOTE: if any at all, only some of these packages will be implemented.

# https://docs.ansible.com/ansible/latest/modules/list_of_packaging_modules.html

# a2s_install_composer / a2s_install_composers

- name: "php"
  include: php/main.yml
  when:
    - "(a2s_betatesting|bool is sameas true)"
    - "(a2s_only_apis is undefined) or ('a2s_install_php' in a2s_only_apis)"
    - "(a2s_except_apis is undefined) or ('a2s_install_php' not in a2s_except_apis)"
  tags:
    - a2s-php

- name: "composer"
  include: composer/main.yml
  when:
    # - "(a2s_betatesting|bool is sameas true)"
    - "(a2s_only_apis is undefined)
      or ('a2s_install_composer' in a2s_only_apis)
      or ('a2s_install_composers' in a2s_only_apis)"
    - "(a2s_except_apis is undefined)
      or (('a2s_install_composer' not in a2s_except_apis)
      and ('a2s_install_composers' not in a2s_except_apis))"
  tags:
    - a2s-install-composer
    - a2s-install-composers
