---
# This is a draft. Can be ignored at this moment

# NOTE: if any at all, only some of these packages will be implemented.

# https://docs.ansible.com/ansible/latest/modules/list_of_packaging_modules.html

# - name: "group-packaging-os.yml: placeholder message"
#   debug:
#     msg: "This is a draft. Not implemented at this moment"

- name: "apt"
  include: apt/main.yml
  when:
    # Skip Windows
    - "(a2s_internal_iswindows is undefined)
    or (a2s_internal_iswindows|bool is sameas false)"
    # # Skip specific run exceptions
    # - "(a2s_only_apis is undefined) or ('a2s_apts' in a2s_only_apis)"
    # - "(a2s_except_apis is undefined) or ('a2s_apts' not in a2s_except_apis)"
    # Load only if variables exist
    - "(a2s_apt_keys is defined) and (a2s_apt_keys[0] is defined)
      or (a2s_apt_repositories is defined) and (a2s_apt_repositories[0] is defined)
      or (a2s_apts is defined) and (a2s_apts[0] is defined)"
  # tags:
  #   - a2s-apts

- name: "package"
  include: package/main.yml
  when:
    - "(a2s_packages is defined)
      and (a2s_packages[0] is defined)"
    - "(a2s_only_apis is undefined) or ('a2s_packages' in a2s_only_apis)"
    - "(a2s_except_apis is undefined) or ('a2s_packages' not in a2s_except_apis)"
  tags:
    - a2s-packages