---
# This is a draft. Can be ignored at this moment

# NOTE: if any at all, only some of these packages will be implemented.

# https://docs.ansible.com/ansible/latest/modules/list_of_packaging_modules.html

- name: "group-packaging-os.yml: placeholder message"
  debug:
    msg: "This is a draft. Not implemented at this moment"
