---
# This is a draft. Can be ignored at this moment

# NOTE: if any at all, only some of these packages will be implemented.

# https://docs.ansible.com/ansible/latest/modules/list_of_packaging_modules.html

# a2s_install_composer / a2s_install_composers