---
# tasks file for ap-application-load-balancer-extras

- name: "AP-ALB-Extras: PHP"
  include: php.yml
  tags:
    - albextras
    - albextras-php
  when: albextras == true and albextras_php == true
  # when: alb_extra_php is defined and alb_extra_php.enabled is defined and alb_extra_php.enabled == true
