---
# FILE:            {{ role_path }}/tasks/main.yml
# LICENSE:         Public Domain

- name: "a2s {{ a2s_version }} welcome message"
  debug:
    msg:
      # a2s_version: "{{ a2s_version }}"
      a2s_betatesting: "{{ a2s_betatesting | default(omit) }}"
      a2s_debug: "{{ a2s_debug | default('undefined') }}"
      a2s_internal_no_log: "{{ a2s_debug | default('undefined') }}"
      a2s_only_apis: "{{ a2s_only_apis | default('undefined') }}"
      a2s_except_apis: "{{ a2s_except_apis | default('undefined') }}"
      a2s_only_apis_groups: "{{ a2s_only_apis_groups | default('undefined') }}"
      a2s_except_apis_groups: "{{ a2s_except_apis_groups | default('undefined') }}"
      a2s_autoinstall_dependencies: "{{ a2s_autoinstall_dependencies | default('undefined') }}"
      a2s_autoinstall_repositories: "{{ a2s_autoinstall_repositories | default('undefined') }}"
      a2s_internal_iswindows: "{{ a2s_internal_iswindows | default('undefined') }}"
      ansible_run_tags: "{{ ansible_run_tags | default('undefined') }}"
      ansible_skip_tags: "{{ ansible_skip_tags | default('undefined') }}"
      node:
        os: "{{ ansible_os_family | default('undefined') | lower }}"
        dist: "{{ ansible_distribution | default('undefined') | lower }}"
        dist_release: "{{ ansible_distribution_release | default('undefined') | lower }}"
        dist_major_ver: "{{ ansible_distribution_major_version | default('undefined') | lower }}"
        ansible_lsb: "{{ ansible_lsb | default('undefined') }}"
        # If behind NAT, this may not represent real public IPv4.
        # Alternative: https://docs.ansible.com/ansible/latest/modules/ipify_facts_module.html
        ansible_default_ipv4: "{{ ansible_default_ipv4.address | default('undefined') }}"
  tags:
    - always

## Variable loading based on node Operational System ___________________________
- name: "OS Family variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ (a2s_iswindows is defined and a2s_iswindows|bool) | ternary('os-family/windows.yml', 'name-of-a-file-that-does-not-exist.yml') }}"
    - "{{ (a2s_vars_osfamily is defined) | ternary(a2s_vars_osfamily, 'name-of-a-file-that-does-not-exist.yml') }}"
    - "os-family/{{ ansible_os_family | default('undefined') | lower }}.yml"
    - "os-family/{{ (ansible_os_family is defined) | ternary('untested','unknown') }}.yml"
  tags:
    - always

- name: "OS Family version variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ (a2s_vars_osfamilyversion is defined) | ternary(a2s_vars_osfamilyversion, 'name-of-a-file-that-does-not-exist.yml') }}"
    - "os-family/os-family-version/{{ ansible_os_family | default('undefined') | lower }}-{{ ansible_distribution_major_version
      | default('undefined')
      | lower }}.yml"
    - "os-family/os-family-version/no-os-family-version-customization.yml"
  tags:
    - always

- name: "Distribution variables (may override OS Family variables, if exist)"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ (a2s_vars_distribution is defined) | ternary(a2s_vars_distribution, 'name-of-a-file-that-does-not-exist.yml') }}"
    - "os-family/distribution/{{ ansible_distribution | default('undefined') | lower }}.yml"
    - "os-family/distribution/no-os-family-customization.yml"
  tags:
    - always

- name: "Specific version distribution variables (may override OS Family and Distribution variables, if exist)"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ (a2s_vars_distribution_version is defined) | ternary(a2s_vars_distribution_version, 'name-of-a-file-that-does-not-exist.yml') }}"
    - "os-family/distribution/version/{{ ansible_distribution | default('undefined') | lower }}-{{ ansible_distribution_major_version
      | default('undefined')
      | lower }}.yml"
    - "os-family/distribution/version/no-distribution-customization.yml"
  tags:
    - always

- name: "Result of pre-calculated variables on this play"
  debug:
    msg:
      a2s_default_user: "{{ a2s_default_user | default('undefined') }}"
      a2s_default_group: "{{ a2s_default_group | default('undefined') }}"
      a2s_default_directory_mode: "{{ a2s_default_directory_mode | default('undefined') }}"
      a2s_default_file_mode: "{{ a2s_default_file_mode | default('undefined') }}"
      a2s_isconteiner: "{{ a2s_isconteiner | default('undefined') }}"
      a2s_install_composer: "{{ a2s_install_composer | default(omit) }}"
      a2s_install_composers: "{{ a2s_install_composers | default(omit) }}"
      a2s_install_php: "{{ a2s_install_php | default(omit) }}"
  tags:
    - always

## Load a2s apis by group ______________________________________________________

- name: "apis-packaging-os.yml"
  # include: "apis-packaging-os.yml"
  # static: false
  include_tasks: "apis-packaging-os.yml"
  when:
    - "(a2s_only_apis_groups is undefined) or ('packaging-os' in a2s_only_apis_groups)"
    - "(a2s_except_apis_groups is undefined) or ('packaging-os' not in a2s_except_apis_groups)"
  tags:
    - a2s-group-packaging-os

- name: "apis-system.yml"
  include_tasks: "apis-system.yml"
  when:
    - "(a2s_only_apis_groups is undefined) or ('system' in a2s_only_apis_groups)"
    - "(a2s_except_apis_groups is undefined) or ('system' not in a2s_except_apis_groups)"
  tags:
    - a2s-group-system

- name: "apis-files.yml"
  include_tasks: "apis-files.yml"
  when:
    - "(a2s_only_apis_groups is undefined) or ('files' in a2s_only_apis_groups)"
    - "(a2s_except_apis_groups is undefined) or ('files' not in a2s_except_apis_groups)"
  tags:
    - a2s-group-files

- name: "apis-packaging-languages.yml"
  include_tasks: "apis-packaging-languages.yml"
  when:
    - "(a2s_only_apis_groups is undefined) or ('packaging-languages' in a2s_only_apis_groups)"
    - "(a2s_except_apis_groups is undefined) or ('packaging-languages' not in a2s_except_apis_groups)"
  tags:
    - a2s-group-packaging-languages

- name: "apis-database.yml"
  include_tasks: "apis-database.yml"
  when:
    - "(a2s_only_apis_groups is undefined) or ('database' in a2s_only_apis_groups)"
    - "(a2s_except_apis_groups is undefined) or ('database' not in a2s_except_apis_groups)"
  tags:
    - a2s-group-database

- name: "apis-a2s-devel.yml"
  include_tasks: "apis-a2s-devel.yml"
  when:
    - "(a2s_only_apis_groups is undefined) or ('a2s-devel' in a2s_only_apis_groups)"
    - "(a2s_except_apis_groups is undefined) or ('a2s-devel' not in a2s_except_apis_groups)"
  tags:
    - a2s-group-a2s-devel

- name: "apis-a2s-extra.yml"
  include_tasks: "apis-a2s-extra.yml"
  when:
    - "(a2s_only_apis_groups is undefined) or ('a2s-extra' in a2s_only_apis_groups)"
    - "(a2s_except_apis_groups is undefined) or ('a2s-extra' not in a2s_except_apis_groups)"
  tags:
    - a2s-group-a2s-extra
