---

# FILE:            {{ role_path }}/tasks/copy/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/copy_module.html
# SEE:             https://docs.ansible.com/ansible/latest/modules/win_copy_module.html

# TODO: implement state: absent for both a2s_copys and a2s_templates even if
#       copy and template does not support it. Check https://github.com/ansible/ansible/issues/6929
#       (fititnt, 2019-01-08 11:48 BRT)

- name: "[files] a2s_copies | Via: debug | a2s_copies_default (override undefined values)"
  debug:
    msg:
      a2s_copies_default: "{{ a2s_copies_default }}"

- name: "[files] a2s_copies | Via: copy | (*nix only) copy files/directories"
  copy:
    dest: "{{ item.dest | default(a2s_copies_default.dest | default(omit)) }}"
    src: "{{ item.src | default(a2s_copies_default.src | default(omit)) }}"

    # Other parameters, by alphabetical order
    attributes: "{{ item.attributes | default(a2s_copies_default.attributes | default(omit)) }}"
    attr: "{{ item.attr | default(a2s_copies_default.attr | default(omit)) }}" # alias for attributes
    backup: "{{ item.backup | default(a2s_copies_default.backup | default(omit)) }}"
    checksum: "{{ item.checksum | default(a2s_copies_default.checksum | default(omit)) }}"
    content: "{{ item.content | default(a2s_copies_default.content | default(omit)) }}"
    decrypt: "{{ item.decrypt | default(a2s_copies_default.decrypt | default(omit)) }}"
    directory_mode: "{{ item.directory_mode | default(a2s_copies_default.directory_mode | default(omit)) }}"
    follow: "{{ item.follow | default(a2s_copies_default.follow | default(omit)) }}"
    force: "{{ item.force | default(a2s_copies_default.force | default(omit)) }}"
    group: "{{ item.group | default(a2s_copies_default.group | default(omit)) }}"
    local_follow: "{{ item.local_follow | default(a2s_copies_default.local_follow | default(omit)) }}"
    mode: "{{ item.mode | default(a2s_copies_default.mode | default(omit)) }}"
    owner: "{{ item.owner | default(a2s_copies_default.owner | default(omit)) }}"
    remote_src: "{{ item.remote_src | default(a2s_copies_default.remote_src | default(omit)) }}"
    selevel: "{{ item.selevel | default(a2s_copies_default.selevel | default(omit)) }}"
    serole: "{{ item.serole | default(a2s_copies_default.serole | default(omit)) }}"
    setype: "{{ item.setype | default(a2s_copies_default.setype | default(omit)) }}"
    seuser: "{{ item.seuser | default(a2s_copies_default.seuser | default(omit)) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(a2s_copies_default.unsafe_writes | default(omit)) }}"
    validate: "{{ item.validate | default(a2s_copies_default.validate | default(omit)) }}"
  with_items: "{{ a2s_copies }}"
  when:
    - "(a2s_internal_iswindows is undefined)
      or (a2s_internal_iswindows|bool is sameas false)"
  notify:
    - "a2s-copy-copies changed"
  tags:
    - a2s-copy-copies

- name: "[files] a2s_copies | Via: win_copy | (Windows only) copy files/directories"
  win_copy:
    dest: "{{ item.dest | default(a2s_copies_default.dest | default(omit)) }}"
    src: "{{ item.src | default(a2s_copies_default.src | default(omit)) }}"

    # Other parameters, by alphabetical order
    backup: "{{ item.backup | default(a2s_copies_default.backup | default(omit)) }}"
    content: "{{ item.content | default(a2s_copies_default.content | default(omit)) }}"
    decrypt: "{{ item.decrypt | default(a2s_copies_default.decrypt | default(omit)) }}"
    force: "{{ item.force | default(a2s_copies_default.force | default(omit)) }}"
    local_follow: "{{ item.local_follow | default(a2s_copies_default.local_follow | default(omit)) }}"
    remote_src: "{{ item.remote_src | default(a2s_copies_default.remote_src | default(omit)) }}"
  with_items: "{{ a2s_copies }}"
  when:
    - "(a2s_internal_iswindows is defined)
      and (a2s_internal_iswindows|bool is sameas true)"
  notify:
    - "a2s-copy-copies changed"
  tags:
    - a2s-copy-copies
