---

# FILE:            {{ role_path }}/tasks/template/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/template_module.html

# TODO: implement state: absent for both a2s_copys and a2s_templates even if
#       copy and template does not support it. Check https://github.com/ansible/ansible/issues/6929
#       (fititnt, 2019-01-08 11:48 BRT)

- name: "[files] a2s_templates  | Via: debug | a2s_templates_default"
  debug:
    msg:
      a2s_templates_default: "{{ a2s_templates_default | to_json }}"
      a2s_templates: "{{ a2s_directories | default('undefined') }}"
  vars:
    # Did Ansible allow NOT evaluate a variable, so this part would not be
    # necessary? (fititnt, 2020-01-20 02:29 BRT)
    item:
      src: '[[ item.src ]]'
      dest: '[[ item.dest ]]'
      attributes: '[[ item.attributes ]]'
      backup: '[[ item.backup ]]'
      block_end_string: '[[ item.block_end_string ]]'
      block_start_string: '[[ item.block_start_string ]]'
      follow: '[[ item.follow ]]'
      force: '[[ item.force ]]'
      group: '[[ item.group ]]'
      lstrip_blocks: '[[ item.lstrip_blocks ]]'
      mode: '[[ item.mode ]]'
      newline_sequence: '[[ item.newline_sequence ]]'
      output_encoding: '[[ item.output_encoding ]]'
      owner: '[[ item.owner ]]'
      selevel: '[[ item.selevel ]]'
      serole: '[[ item.serole ]]'
      setype: '[[ item.setype ]]'
      seuser: '[[ item.seuser ]]'
      trim_blocks: '[[ item.trim_blocks ]]'
      unsafe_writes: '[[ item.unsafe_writes ]]'
      validate: '[[ item.validate ]]'
      variable_end_string: '[[ item.variable_end_string ]]'
      variable_start_string: '[[ item.variable_start_string ]]'
      var: "[[ item.var ]]"
      var1: "[[ item.var1 ]]"
      var2: "[[ item.var2 ]]"
      var3: "[[ item.var3 ]]"
      a: "[[ item.a ]]"
      b: "[[ item.b ]]"
      c: "[[ item.c ]]"
      x: "[[ item.x ]]"
      y: "[[ item.y ]]"
      z: "[[ item.z ]]"
  # We allow this fail because the user may be using and variable that only
  # exist when evaluating the loop and this variable was not expected.
  ignore_errors: yes

- name: "[files] a2s_templates | Via: file | template a file on destiny"
  template:
    src: "{{ item.src | default(a2s_templates_default.src | default(omit)) }}"
    dest: "{{ item.dest | default(a2s_templates_default.dest | default(omit)) }}"
    attributes: "{{ item.attributes | default(a2s_templates_default.attributes | default(omit)) }}"
    backup: "{{ item.backup | default(a2s_templates_default.backup | default(omit)) }}"
    block_end_string: "{{ item.block_end_string | default(a2s_templates_default.block_end_string | default(omit)) }}"
    block_start_string: "{{ item.block_start_string | default(a2s_templates_default.block_start_string | default(omit)) }}"
    follow: "{{ item.follow | default(a2s_templates_default.follow | default(omit)) }}"
    force: "{{ item.force | default(a2s_templates_default.force | default(omit)) }}"
    group: "{{ item.group | default(a2s_templates_default.group | default(omit)) }}"
    lstrip_blocks: "{{ item.lstrip_blocks | default(a2s_templates_default.lstrip_blocks | default(omit)) }}"
    mode: "{{ item.mode | default(a2s_templates_default.mode | default(omit)) }}"
    newline_sequence: "{{ item.newline_sequence | default(a2s_templates_default.newline_sequence | default(omit)) }}"
    output_encoding: "{{ item.output_encoding | default(a2s_templates_default.output_encoding | default(omit)) }}"
    owner: "{{ item.owner | default(a2s_templates_default.owner | default(omit)) }}"
    selevel: "{{ item.selevel | default(a2s_templates_default.selevel | default(omit)) }}"
    serole: "{{ item.serole | default(a2s_templates_default.serole | default(omit)) }}"
    setype: "{{ item.setype | default(a2s_templates_default.setype | default(omit)) }}"
    seuser: "{{ item.seuser | default(a2s_templates_default.seuser | default(omit)) }}"
    trim_blocks: "{{ item.trim_blocks | default(a2s_templates_default.trim_blocks | default(omit)) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(a2s_templates_default.unsafe_writes | default(omit)) }}"
    validate: "{{ item.validate | default(a2s_templates_default.validate | default(omit)) }}"
    variable_end_string: "{{ item.variable_end_string | default(a2s_templates_default.variable_end_string | default(omit)) }}"
    variable_start_string: "{{ item.variable_start_string | default(a2s_templates_default.variable_start_string | default(omit)) }}"
  with_items: "{{ a2s_templates }}"
  notify:
    - "a2s-template-templates changed"
  tags:
    - a2s-template-templates
