---

# FILE:            {{ role_path }}/tasks/devel-nginx/install.yml
# LICENSE:         Public Domain
#
# SEE:             https://docs.ansible.com/ansible/latest/modules/package_module.html

- name: "[a2s-devel] devel-nginx | install: prerequisite packages"
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ a2s_internal_devel_nginx_prerequisites_packages }}"
  when:
    - "(a2s_internal_devel_nginx_prerequisites_packages is defined)
       and (a2s_internal_devel_nginx_prerequisites_packages[0] is defined)"

- name: "[a2s-devel] devel-nginx | install | (*nix) install: package install nginx"
  package:
    name: "nginx"
    state: "present"
  # ignore_errors: true
  when:
    - "(a2s_internal_iswindows is undefined)
      or (a2s_internal_iswindows|bool is sameas false)"

- name: "[a2s-devel] devel-nginx | install | start nginx"
  service:
    name: nginx
    state: started
  # ignore_errors: yes
  ignore_errors: "{{ a2s_isconteiner | default(false) }}"
  when:
    - "(a2s_internal_iswindows is undefined)
      or (a2s_internal_iswindows|bool is sameas false)"

- name: "[a2s-devel] devel-nginx | install | enable nginx"
  service:
    name: nginx
    enabled: yes
  when:
    - "(a2s_isconteiner is undefined) or (a2s_isconteiner|bool is not sameas true)"
    - "(a2s_internal_iswindows is undefined)
      or (a2s_internal_iswindows|bool is sameas false)"