---

# FILE:            {{ role_path }}/tasks/devel-nginx/install.yml
# LICENSE:         Public Domain
#
# SEE:             https://docs.ansible.com/ansible/latest/modules/package_module.html

- name: "devel-nginx | install: prerequisite packages"
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ a2s_internal_devel_nginx_prerequisites_packages }}"
  when:
    - "(a2s_internal_devel_nginx_prerequisites_packages is defined)
       and (a2s_internal_devel_nginx_prerequisites_packages[0] is defined)"

- name: "devel-nginx | install | (*nix) install: package install nginx"
  package:
    name: "nginx"
    state: "present"
  # ignore_errors: true
  when:
    - "(a2s_internal_iswindows is undefined)
      or (a2s_internal_iswindows|bool is sameas false)"

- name: "devel-nginx | install | start and enable: nginx"
  service:
    name: nginx
    state: started
    enabled: yes
  when:
    - "(a2s_internal_iswindows is undefined)
      or (a2s_internal_iswindows|bool is sameas false)"