---

# FILE:            {{ role_path }}/tasks/php/repository/main.yml
# LICENSE:         Public Domain

# https://computingforgeeks.com/how-to-install-php-7-4-on-centos-rhel-8/
# https://computingforgeeks.com/how-to-install-php-on-ubuntu/

- name: "php | repository | apt_key (Debian Family)"
  apt_key:
    url: "{{ a2s_internal_php_apt_key.url | default(omit) }}"
    state: "{{ a2s_internal_php_apt_key.state | default(omit) }}"
    id: "{{ a2s_internal_php_apt_key.id | default(omit) }}"
    keyring: "{{ a2s_internal_php_apt_key.keyring | default(omit) }}"
  when:
    - "(a2s_internal_php_apt_key is defined) and (a2s_internal_php_apt_key.url is defined)"

- name: "php | repository | apt_repository (Debian Family)"
  apt_repository:
    repo: "{{ a2s_internal_php_apt_repository.repo | default(omit) }}"
    state: "{{ a2s_internal_php_apt_repository.state | default(omit) }}"
    filename: "{{ a2s_internal_php_apt_repository.filename | default(omit) }}"
    # update_cache: false
  # ignore_errors: true #TODO remove this later
  when:
    - "(a2s_internal_php_apt_repository is defined) and (a2s_internal_php_apt_repository.repo is defined)"
