---

# FILE:            {{ role_path }}/tasks/users/templates.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/templates_module.html

- name: "[system] a2s_users[n]templates | Via: template | template out a file for this user"
  template:
    src: "{{ item.1.src | default(this_default.src | default(omit)) }}"
    dest: "{{ item.1.dest | default(this_default.dest | default(omit)) }}"
    attributes: "{{ item.1.attributes | default(this_default.attributes | default(omit)) }}"
    backup: "{{ item.1.backup | default(this_default.backup | default(omit)) }}"
    block_end_string: "{{ item.1.block_end_string | default(this_default.block_end_string | default(omit)) }}"
    block_start_string: "{{ item.1.block_start_string | default(this_default.block_start_string | default(omit)) }}"
    follow: "{{ item.1.follow | default(this_default.follow | default(omit)) }}"
    force: "{{ item.1.force | default(this_default.force | default(omit)) }}"
    group: "{{ item.1.group | default(this_default.group | default(omit)) }}"
    lstrip_blocks: "{{ item.1.lstrip_blocks | default(this_default.lstrip_blocks | default(omit)) }}"
    mode: "{{ item.1.mode | default(this_default.mode | default(omit)) }}"
    newline_sequence: "{{ item.1.newline_sequence | default(this_default.newline_sequence | default(omit)) }}"
    output_encoding: "{{ item.1.output_encoding | default(this_default.output_encoding | default(omit)) }}"
    owner: "{{ item.1.owner | default(this_default.owner | default(omit)) }}"
    selevel: "{{ item.1.selevel | default(this_default.selevel | default(omit)) }}"
    serole: "{{ item.1.serole | default(this_default.serole | default(omit)) }}"
    setype: "{{ item.1.setype | default(this_default.setype | default(omit)) }}"
    seuser: "{{ item.1.seuser | default(this_default.seuser | default(omit)) }}"
    trim_blocks: "{{ item.1.trim_blocks | default(this_default.trim_blocks | default(omit)) }}"
    unsafe_writes: "{{ item.1.unsafe_writes | default(this_default.unsafe_writes | default(omit)) }}"
    validate: "{{ item.1.validate | default(this_default.validate | default(omit)) }}"
    variable_end_string: "{{ item.1.variable_end_string | default(this_default.variable_end_string | default(omit)) }}"
    variable_start_string: "{{ item.1.variable_start_string | default(this_default.variable_start_string | default(omit)) }}"
  with_subelements:
    - "{{ a2s_users }}"
    - "templates"
    - skip_missing: true
  vars:
    this_default: "{{ a2s_users_default.templates_default | default(a2s_users_templates_default) }}"
  notify:
    - "a2s-user-templates changed"
  tags:
    - a2s-user-templates
