---

# FILE:            {{ role_path }}/tasks/users/templates.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/templates_module.html

# this is a draft

- name: "[system] user| Via: debug | templates: template out file and add to user home directory"
  template:
    hash_host: "{{ item.1.hash_host | default(omit) }}"
    key: "{{ item.1.key | default(omit) }}"
    name: "{{ item.1.name | default(omit) }}"
    path: "{{ item.1.path | default(omit) }}"
     # host is alias for name
    host: "{{ item.1.host | default(omit) }}"
    state: "{{ item.1.state | default(omit) }}"
  with_subelements:
    - "{{ a2s_users }}"
    - "templates"
    - skip_missing: true
  notify:
    - "a2s-user-templates changed"
  tags:
    - a2s-user-templates
