---

# FILE:            {{ role_path }}/tasks/users/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/user_module.html
# SEE:             https://docs.ansible.com/ansible/latest/modules/win_user_module.html

- name: "[system] users | user (*nix): add/remove users [a2s_users_default: {{ a2s_users_default }}]"
  user:
    name: "{{ item.name }}"
    state: "{{ item.state | default(a2s_users_default.state | default(omit)) }}"
    append: "{{ item.append | default(a2s_users_default.append | default(omit)) }}"
    authorization: "{{ item.authorization | default(a2s_users_default.authorization | default(omit)) }}"
    comment:  "{{ item.comment | default(a2s_users_default.comment | default(omit)) }}"
    create_home:  "{{ item.create_home | default(a2s_users_default.create_home | default(omit)) }}"
    expires:  "{{ item.expires | default(a2s_users_default.expires | default(omit)) }}"
    force:  "{{ item.force | default(a2s_users_default.force | default(omit)) }}"
    generate_ssh_key:  "{{ item.generate_ssh_key | default(a2s_users_default.generate_ssh_key | default(omit)) }}"
    group: "{{ item.group | default(a2s_users_default.group | default(omit)) }}"

    # TODO: implement defaults here
    groups: "{{ item.groups | default([]) | join(',') or omit }}"
    hidden: "{{ item.hidden | default([]) | join(',') or omit }}"
    home:  "{{ item.home | default(a2s_users_default.home | default(omit)) }}"
    local:  "{{ item.local | default(a2s_users_default.local | default(omit)) }}"
    login_class:  "{{ item.login_class | default(a2s_users_default.login_class | default(omit)) }}"
    move_home:  "{{ item.move_home | default(a2s_users_default.move_home | default(omit)) }}"
    non_unique:  "{{ item.non_unique | default(a2s_users_default.non_unique | default(omit)) }}"
    password:  "{{ item.password | default(a2s_users_default.password | default(omit)) }}"
    password_lock:  "{{ item.password_lock | default(a2s_users_default.password_lock | default(omit)) }}"
    profile:  "{{ item.profile | default(a2s_users_default.profile | default(omit)) }}"
    remove:  "{{ item.remove | default(a2s_users_default.remove | default(omit)) }}"
    role:  "{{ item.role | default(a2s_users_default.role | default(omit)) }}"
    seuser:  "{{ item.seuser | default(a2s_users_default.seuser | default(omit)) }}"
    shell:  "{{ item.shell | default(a2s_users_default.shell | default(omit)) }}"
    skeleton: "{{ item.skeleton | default(a2s_users_default.skeleton | default(omit)) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default(a2s_users_default.ssh_key_bits | default(omit)) }}"
    ssh_key_comment: "{{ item.ssh_key_comment | default(a2s_users_default.ssh_key_comment | default(omit)) }}"
    ssh_key_file: "{{ item.ssh_key_file | default(a2s_users_default.ssh_key_file | default(omit)) }}"
    ssh_key_passphrase: "{{ item.ssh_key_passphrase | default(a2s_users_default.ssh_key_passphrase | default(omit)) }}"
    ssh_key_type: "{{ item.ssh_key_type | default(a2s_users_default.ssh_key_type | default(omit)) }}"
    system: "{{ item.system | default(a2s_users_default.system | default(omit)) }}"
    uid: "{{ item.uid | default(a2s_users_default.uid | default(omit)) }}"
    update_password: "{{ item.update_password | default(a2s_users_default.update_password | default(omit)) }}"
  with_items: "{{ a2s_users }}"
  when:
    - "(a2s_internal_iswindows is undefined)
      or (a2s_internal_iswindows|bool is sameas false)"
  notify:
    - "a2s-user-users changed"
  tags:
    - a2s-user-users

- name: "[system] users | user (Windows): add/remove users"
  win_user:
    name: "{{ item.name }}"
    state: "{{ item.state | default(a2s_users_default.state | default(omit)) }}"
    account_disabled: "{{ item.account_disabled | default(a2s_users_default.account_disabled | default(omit)) }}"

    # TODO: implement defaults here
    account_locked: "{{ item.account_locked | default([]) | join(',') or omit }}"
    fullname:  "{{ item.fullname | default(a2s_users_default.fullname | default(omit)) }}"
    groups:  "{{ item.groups | default(a2s_users_default.groups | default(omit)) }}"
    groups_action:  "{{ item.groups_action | default(a2s_users_default.groups_action | default(omit)) }}"
    password:  "{{ item.password | default(a2s_users_default.password | default(omit)) }}"
    password_expired:  "{{ item.password_expired | default(a2s_users_default.password | default(omit)) }}"
    password_never_expires:  "{{ item.password_never_expires | default(a2s_users_default.password_never_expires | default(omit)) }}"
    update_password:  "{{ item.update_password | default(a2s_users_default.update_password | default(omit)) }}"
    user_cannot_change_password:  "{{ item.user_cannot_change_password | default(a2s_users_default.user_cannot_change_password | default(omit)) }}"
  with_items: "{{ a2s_users }}"
  when:
    - "(a2s_internal_iswindows is defined)
      and (a2s_internal_iswindows|bool is sameas true)"
  notify:
    - "a2s-user-users changed"
  tags:
    - a2s-user-users