---

# FILE:            {{ role_path }}/tasks/rclone/config.yml
# LICENSE:         Public Domain
#
# SEE:             https://docs.ansible.com/ansible/latest/modules/template_module.html
#

- name: "rclone | config.yml [{{ a2s_rclone }}]"
  template:
    src: "rclone/rclone.conf.j2"
    dest: "{{ a2s_rclone.path_conf | default('/root/.config/rclone/rclone.conf') }}"
    attributes: "{{ item.attributes | default(omit) }}"
    backup: "{{ item.backup | default(omit) }}"
    block_end_string: "{{ item.block_end_string | default(omit) }}"
    block_start_string: "{{ item.block_start_string | default(omit) }}"
    follow: "{{ item.follow | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    lstrip_blocks: "{{ item.lstrip_blocks | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    newline_sequence: "{{ item.newline_sequence | default(omit) }}"
    output_encoding: "{{ item.output_encoding | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    trim_blocks: "{{ item.trim_blocks | default(omit) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(omit) }}"
    validate: "{{ item.validate | default(omit) }}"
    variable_end_string: "{{ item.variable_end_string | default(omit) }}"
    variable_start_string: "{{ item.variable_start_string | default(omit) }}"
  with_items: "{{ a2s_rclone }}"
  notify:
    - "a2s-rclone-conf changed"
  tags:
    - a2s-rclone-conf
