---
# FILE:            {{ role_path }}/tasks/rclone/main.yml
# LICENSE:         Public Domain

- name: "rclone | main.yml"
  include: "{{ role_path }}/tasks/rclone/install.yml"

- name: "rclone | main.yml"
  include: "{{ role_path }}/tasks/rclone/config.yml"
  when:
    - "(a2s_rclone is defined) and (a2s_rclone.confs is defined)"
