---

# FILE:            {{ role_path }}/tasks/php/main.yml
# LICENSE:         Public Domain

- name: "[packaging-languages] php | main.yml"
  debug:
    msg: "This is a draft. Not implemented at the moment"
  when:
    - "(a2s_betatesting|bool is sameas false)"

- name: "[packaging-languages] php | repository"
  include: "{{ role_path }}/tasks/php/repository/main.yml"
  when:
    - "(a2s_betatesting|bool is sameas true)"
    - "(a2s_autoinstall_repositories|bool is sameas true)"
  tags:
    - s2s-php-repository

- name: "[packaging-languages] php | install php"
  include: "{{ role_path }}/tasks/php/install/main.yml"
  when:
    - "(a2s_betatesting|bool is sameas true)"
    - "(a2s_install_php is defined and a2s_install_php[0] is defined)"
  tags:
    - s2s-install-php
